name: matrix build

on: 
  push:
  pull-request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: verify python version
        run: python --version
      - name: run test
        run: echo "running tests..."


  
